src: Rename jobs directories to match job names
SUSE/scf-helper-release pull request #2
Opened 2018-05-04 17:09 UTC by alexjh

Commit taken from uaa-fissile-release:994e67413ab26a072dd1d20d226cb875da13a713

New BOSH appears to validate that the job names match the directory they
reside in. Seems like a reasonable check.

2018-05-04 22:16 UTC, mook-as requested changes
`cf-acceptance-tests` needs a bump; please check if I've missed other submodules? I don't _think_ I have, but I'm a little lost with all the submodules.

2018-05-04 22:24 UTC, alexjh commented
No, that looks like the only one that changed under `src/scf-helper-release` in https://github.com/SUSE/scf.

2018-05-04 22:27 UTC, alexjh commented
In hindsight, what I should have done was quickly split off the submodule with no changes, made the PR into SCF, then made a new PR for UAA and its changes. :confused:

2018-05-07 21:07 UTC, mook-as approved these changes

2018-05-07 21:07 UTC, merged